"""add tool_templates table

Revision ID: 1455d61d08eb
Revises: 7379dc2ffd48
Create Date: 2026-04-22 15:45:09.460138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1455d61d08eb'
down_revision: Union[str, Sequence[str], None] = '7379dc2ffd48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('etl_sql', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_templates_id'), 'tool_templates', ['id'], unique=False)
    op.create_index(op.f('ix_tool_templates_type_slug'), 'tool_templates', ['type_slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_templates_type_slug'), table_name='tool_templates')
    op.drop_index(op.f('ix_tool_templates_id'), table_name='tool_templates')
    op.drop_table('tool_templates')
    # ### end Alembic commands ###
