"""instrument_list_and_audit

Revision ID: 4f993b22847c
Revises: 62ead3a09619
Create Date: 2026-04-20 16:16:06.195567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f993b22847c'
down_revision: Union[str, Sequence[str], None] = '62ead3a09619'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('tool', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('row_id', sa.Integer(), nullable=True),
    sa.Column('field', sa.String(length=100), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_id'), 'audit_log', ['id'], unique=False)
    op.create_table('instrument_list_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_index(op.f('ix_instrument_list_notes_id'), 'instrument_list_notes', ['id'], unique=False)
    op.create_table('instrument_list_revs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('current_rev', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_index(op.f('ix_instrument_list_revs_id'), 'instrument_list_revs', ['id'], unique=False)
    op.create_table('instrument_list_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('rev', sa.String(length=20), nullable=True),
    sa.Column('fase', sa.String(length=50), nullable=True),
    sa.Column('pid', sa.String(length=100), nullable=True),
    sa.Column('tag', sa.String(length=100), nullable=False),
    sa.Column('servizio', sa.String(length=200), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('standard', sa.String(length=100), nullable=True),
    sa.Column('classe', sa.String(length=50), nullable=True),
    sa.Column('attacco', sa.String(length=100), nullable=True),
    sa.Column('range', sa.String(length=100), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('row_log', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'tag', name='uq_instrument_tag_per_project')
    )
    op.create_index(op.f('ix_instrument_list_rows_id'), 'instrument_list_rows', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_instrument_list_rows_id'), table_name='instrument_list_rows')
    op.drop_table('instrument_list_rows')
    op.drop_index(op.f('ix_instrument_list_revs_id'), table_name='instrument_list_revs')
    op.drop_table('instrument_list_revs')
    op.drop_index(op.f('ix_instrument_list_notes_id'), table_name='instrument_list_notes')
    op.drop_table('instrument_list_notes')
    op.drop_index(op.f('ix_audit_log_id'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
