"""add tool_type to tools

Revision ID: 7379dc2ffd48
Revises: df886ba88f86
Create Date: 2026-04-22 15:21:10.941870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7379dc2ffd48'
down_revision: Union[str, Sequence[str], None] = 'df886ba88f86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tools', sa.Column('tool_type', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tools', 'tool_type')
    # ### end Alembic commands ###
