"""table_engine

Revision ID: eef75a17d912
Revises: 4f993b22847c
Create Date: 2026-04-20 17:34:44.864921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eef75a17d912'
down_revision: Union[str, Sequence[str], None] = '4f993b22847c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('query_config', sa.Text(), nullable=True),
    sa.Column('current_rev', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'slug', name='uq_tool_slug_per_project')
    )
    op.create_index(op.f('ix_tools_id'), 'tools', ['id'], unique=False)
    op.create_table('tool_columns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('col_type', sa.String(length=50), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('formula', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tool_id', 'slug', name='uq_column_slug_per_tool')
    )
    op.create_index(op.f('ix_tool_columns_id'), 'tool_columns', ['id'], unique=False)
    op.create_table('tool_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('rev', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('row_log', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_rows_id'), 'tool_rows', ['id'], unique=False)
    op.create_table('tool_cells',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('row_id', sa.Integer(), nullable=False),
    sa.Column('column_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('is_overridden', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['column_id'], ['tool_columns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['row_id'], ['tool_rows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('row_id', 'column_id', name='uq_cell_per_row_column')
    )
    op.create_index(op.f('ix_tool_cells_id'), 'tool_cells', ['id'], unique=False)
    op.drop_index(op.f('ix_instrument_list_rows_id'), table_name='instrument_list_rows')
    op.drop_table('instrument_list_rows')
    op.drop_index(op.f('ix_instrument_list_revs_id'), table_name='instrument_list_revs')
    op.drop_table('instrument_list_revs')
    op.drop_index(op.f('ix_instrument_list_notes_id'), table_name='instrument_list_notes')
    op.drop_table('instrument_list_notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instrument_list_notes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_index(op.f('ix_instrument_list_notes_id'), 'instrument_list_notes', ['id'], unique=False)
    op.create_table('instrument_list_revs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('current_rev', sa.VARCHAR(length=20), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_index(op.f('ix_instrument_list_revs_id'), 'instrument_list_revs', ['id'], unique=False)
    op.create_table('instrument_list_rows',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('rev', sa.VARCHAR(length=20), nullable=True),
    sa.Column('fase', sa.VARCHAR(length=50), nullable=True),
    sa.Column('pid', sa.VARCHAR(length=100), nullable=True),
    sa.Column('tag', sa.VARCHAR(length=100), nullable=False),
    sa.Column('servizio', sa.VARCHAR(length=200), nullable=True),
    sa.Column('tipo', sa.VARCHAR(length=50), nullable=True),
    sa.Column('standard', sa.VARCHAR(length=100), nullable=True),
    sa.Column('classe', sa.VARCHAR(length=50), nullable=True),
    sa.Column('attacco', sa.VARCHAR(length=100), nullable=True),
    sa.Column('range', sa.VARCHAR(length=100), nullable=True),
    sa.Column('note', sa.TEXT(), nullable=True),
    sa.Column('row_log', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'tag', name=op.f('uq_instrument_tag_per_project'))
    )
    op.create_index(op.f('ix_instrument_list_rows_id'), 'instrument_list_rows', ['id'], unique=False)
    op.drop_index(op.f('ix_tool_cells_id'), table_name='tool_cells')
    op.drop_table('tool_cells')
    op.drop_index(op.f('ix_tool_rows_id'), table_name='tool_rows')
    op.drop_table('tool_rows')
    op.drop_index(op.f('ix_tool_columns_id'), table_name='tool_columns')
    op.drop_table('tool_columns')
    op.drop_index(op.f('ix_tools_id'), table_name='tools')
    op.drop_table('tools')
    # ### end Alembic commands ###
